# Use official Node.js image
FROM node:latest

RUN npm install -g nodemon

# Set working directory inside the container
WORKDIR /BASIC-APP

# Copy the rest of the app files
COPY . .

RUN npm install

# Expose port
EXPOSE 5500

# Start the app
# CMD ["node", "index.js"]
CMD ["npm", "run", "dev"]